# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time

driver = webdriver.Chrome()
driver.get("https://idemo.bspb.ru/auth?response_type=code&client_id=1&redirect_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fsuccess&prefetch_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fprefetch&force_new_session=true&state=%2Foverview")
driver.set_window_size(1920, 1040)
# Вход в ЛК Пользователя
driver.find_element(By.ID, "login-button").click()
driver.find_element(By.ID, "login-otp-button").click()
time.sleep(5)

# Выбор пользователя "Королёва Ольга"
driver.find_element(By.ID, "representee-list").click()
driver.find_element(By.LINK_TEXT , "Королёва Ольга").click()

# Проверка табов в ЛК Пользователя
driver.find_element(By.ID, "bank-overview").click()
driver.find_element(By.ID, "accounts-index").click()
driver.find_element(By.ID, "payments-form").click()
driver.find_element(By.ID, "cards-overview-index").click()
driver.find_element(By.ID, "deposits-index").click()
driver.find_element(By.ID, "loans-index").click()
driver.find_element(By.ID, "externaltraderoom-index").click()
driver.find_element(By.ID, "insurance-vehicle").click()
time.sleep(5)
# Проверка функции "Умный перевод"
time.sleep(5)
driver.find_element(By.ID, "payments-form").click()
driver.find_element(By.ID, "smart-payment").send_keys("Rjhjktdf")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys("Королёва Ольга")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys("иван тютин")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys("Королёва")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys("ОльГА корлёВа ")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys(",./**&^&^")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys("5081781004800")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys("50817810048000104468")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys("4797291745786192")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys("479729174578619")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys("47972957861fdg")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys("47972917861@#@")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys(" ")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys("78254023847825400000")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys("7825402384")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()
driver.find_element(By.ID, "smart-payment").send_keys("+7987 123 45 98")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()

driver.find_element(By.ID, "smart-payment").send_keys("+7887 123 45 98")
time.sleep(2)
driver.find_element(By.ID, "smart-payment").clear()

driver.find_element(By.ID, "bank-overview").click()

# Выбор пользователя "ОАО Коудборн"
driver.find_element(By.ID, "representee-list").click()
driver.find_element(By.LINK_TEXT , "ОАО \"Коудборн\"").click()
time.sleep(5)
driver.find_element(By.ID, "close-alerts-dialog").click()
# Проверка табов в ЛК Пользователя
driver.find_element(By.ID, "bank-overview").click()
driver.find_element(By.ID, "accounts-index").click()
driver.find_element(By.ID, "payments-form").click()
driver.find_element(By.ID, "corporate-payrolls-index").click()
driver.find_element(By.ID, "corporate-cards-cardsoverview-index").click()
driver.find_element(By.ID, "deposits-index").click()
driver.find_element(By.ID, "corporate-loans-index").click()
driver.find_element(By.ID, "currencyoverview-currencyoverview-index").click()
driver.find_element(By.ID, "corporateServices").click()
time.sleep(2)

# Выбор пользователя "ИП Морозов Павел Изяславович"
driver.find_element(By.ID, "representee-list").click()
driver.find_element(By.LINK_TEXT , "ИП \"Морозов Павел Изяславович\"").click()
time.sleep(2)

# Проверка табов в ЛК Пользователя
driver.find_element(By.ID, "bank-overview").click()
driver.find_element(By.ID, "accounts-index").click()
driver.find_element(By.ID, "payments-form").click()
driver.find_element(By.ID, "corporate-payrolls-index").click()
driver.find_element(By.ID, "corporate-cards-cardsoverview-index").click()
driver.find_element(By.ID, "deposits-index").click()
driver.find_element(By.ID, "corporate-loans-index").click()
driver.find_element(By.ID, "currencyoverview-currencyoverview-index").click()
driver.find_element(By.ID, "corporateServices").click()

