# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBspbtabclick():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_bspbtabclick(self):
    # Test name: bspb-tab_click
    # Step # | name | target | value
    # 1 | open | https://idemo.bspb.ru/ | 
    self.driver.get("https://idemo.bspb.ru/")
    # 2 | click | id=login-button | 
    self.driver.find_element(By.ID, "login-button").click()
    # 3 | click | id=login-otp-button | 
    self.driver.find_element(By.ID, "login-otp-button").click()
    # 4 | click | css=.filter-option | 
    self.driver.find_element(By.CSS_SELECTOR, ".filter-option").click()
    # 5 | click | css=.filter-option | 
    self.driver.find_element(By.CSS_SELECTOR, ".filter-option").click()
    # 6 | click | css=.representee-private > .text | 
    self.driver.find_element(By.CSS_SELECTOR, ".representee-private > .text").click()
    # 7 | click | id=bank-overview | 
    self.driver.find_element(By.ID, "bank-overview").click()
    # 8 | click | id=accounts-index | 
    self.driver.find_element(By.ID, "accounts-index").click()
    # 9 | click | id=payments-form | 
    self.driver.find_element(By.ID, "payments-form").click()
    # 10 | click | id=cards-overview-index | 
    self.driver.find_element(By.ID, "cards-overview-index").click()
    # 11 | click | id=deposits-index | 
    self.driver.find_element(By.ID, "deposits-index").click()
    # 12 | click | id=loans-index | 
    self.driver.find_element(By.ID, "loans-index").click()
    # 13 | click | id=externaltraderoom-index | 
    self.driver.find_element(By.ID, "externaltraderoom-index").click()
    # 14 | click | id=insurance-vehicle | 
    self.driver.find_element(By.ID, "insurance-vehicle").click()
    # 15 | click | css=.filter-option | 
    self.driver.find_element(By.CSS_SELECTOR, ".filter-option").click()
    # 16 | click | linkText=ОАО "Коудборн" | 
    self.driver.find_element(By.LINK_TEXT, "ОАО \"Коудборн\"").click()
    # 17 | click | id=close-alerts-dialog | 
    self.driver.find_element(By.ID, "close-alerts-dialog").click()
    # 18 | click | id=bank-overview | 
    self.driver.find_element(By.ID, "bank-overview").click()
    # 19 | mouseDownAt | css=.modal-backdrop | 428,146
    element = self.driver.find_element(By.CSS_SELECTOR, ".modal-backdrop")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 20 | mouseMoveAt | css=.modal-backdrop | 428,146
    element = self.driver.find_element(By.CSS_SELECTOR, ".modal-backdrop")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 21 | mouseUpAt | css=.modal-backdrop | 428,146
    element = self.driver.find_element(By.CSS_SELECTOR, ".modal-backdrop")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 22 | click | css=.modal-backdrop | 
    self.driver.find_element(By.CSS_SELECTOR, ".modal-backdrop").click()
    # 23 | mouseUp | id=accounts-index | 
    element = self.driver.find_element(By.ID, "accounts-index")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 24 | click | id=corporate-payrolls-index | 
    self.driver.find_element(By.ID, "corporate-payrolls-index").click()
    # 25 | click | id=corporate-cards-cardsoverview-index | 
    self.driver.find_element(By.ID, "corporate-cards-cardsoverview-index").click()
    # 26 | click | id=deposits-index | 
    self.driver.find_element(By.ID, "deposits-index").click()
    # 27 | click | id=corporate-loans-index | 
    self.driver.find_element(By.ID, "corporate-loans-index").click()
    # 28 | click | id=currencyoverview-currencyoverview-index | 
    self.driver.find_element(By.ID, "currencyoverview-currencyoverview-index").click()
    # 29 | click | css=#corporateServices > .dropdown-toggle | 
    self.driver.find_element(By.CSS_SELECTOR, "#corporateServices > .dropdown-toggle").click()
    # 30 | click | css=#corporateServices > .dropdown-toggle | 
    self.driver.find_element(By.CSS_SELECTOR, "#corporateServices > .dropdown-toggle").click()
    # 31 | click | css=#corporateServices > .dropdown-toggle | 
    self.driver.find_element(By.CSS_SELECTOR, "#corporateServices > .dropdown-toggle").click()
    # 32 | click | css=#corporateServices > .dropdown-toggle | 
    self.driver.find_element(By.CSS_SELECTOR, "#corporateServices > .dropdown-toggle").click()
    # 33 | click | css=.filter-option | 
    self.driver.find_element(By.CSS_SELECTOR, ".filter-option").click()
    # 34 | click | css=.active .text | 
    self.driver.find_element(By.CSS_SELECTOR, ".active .text").click()
    # 35 | click | id=bank-overview | 
    self.driver.find_element(By.ID, "bank-overview").click()
    # 36 | click | css=.modal-backdrop | 
    self.driver.find_element(By.CSS_SELECTOR, ".modal-backdrop").click()
    # 37 | click | id=accounts-index | 
    self.driver.find_element(By.ID, "accounts-index").click()
    # 38 | click | id=payments-form | 
    self.driver.find_element(By.ID, "payments-form").click()
    # 39 | click | id=corporate-payrolls-index | 
    self.driver.find_element(By.ID, "corporate-payrolls-index").click()
    # 40 | click | id=corporate-cards-cardsoverview-index | 
    self.driver.find_element(By.ID, "corporate-cards-cardsoverview-index").click()
    # 41 | click | id=deposits-index | 
    self.driver.find_element(By.ID, "deposits-index").click()
    # 42 | click | id=corporate-loans-index | 
    self.driver.find_element(By.ID, "corporate-loans-index").click()
    # 43 | click | id=currencyoverview-currencyoverview-index | 
    self.driver.find_element(By.ID, "currencyoverview-currencyoverview-index").click()
    # 44 | click | css=#corporateServices > .dropdown-toggle | 
    self.driver.find_element(By.CSS_SELECTOR, "#corporateServices > .dropdown-toggle").click()
  
